services:
  db:
    image: postgres
    container_name: db-cd-ci
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test


  node_app:
    container_name: node_app
    build: .
    ports:
      - 6000:6000
    depends_on:
      - db
    env_file:
      - .env.test
