name: pull request
on: [pull_request]
jobs:
  PullRequest:
    runs_on: ubuntu_latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "102545"
          envkey_POSTGRES_DB: "students"
          envkey_DATABASE_URL: "postgresql://postgres:102545@db-cd-ci:5432/students__tests"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app npm run test
